
services:
  - type: web
    name: manus  # ← عدلي الاسم إذا كان مختلف عن اسم خدمتك في Render
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
